from .parse_values import parse_str, parse_bool, parse_date, parse_int, parse_str_array 

def get_raw_obj(parts):
    (
        wiki_db,
        event_entity,
        event_type,
        event_timestamp,
        event_comment,

        event_user_id,
        event_user_text_historical,
        event_user_text,
        event_user_blocks_historical,
        event_user_blocks,
        event_user_groups_historical,
        event_user_groups,
        event_user_is_bot_by_historical,
        event_user_is_bot_by,
        event_user_is_created_by_self,
        event_user_is_created_by_system,
        event_user_is_created_by_peer,
        event_user_is_anonymous,
        event_user_registration_timestamp,
        event_user_creation_timestamp,
        event_user_first_edit_timestamp,
        event_user_revision_count,
        event_user_seconds_since_previous_revision,

        page_id,
        page_title_historical,
        page_title,
        page_namespace_historical,
        page_namespace_is_content_historical,
        page_namespace,
        page_namespace_is_content,
        page_is_redirect,
        page_is_deleted,
        page_creation_timestamp,
        page_first_edit_timestamp,
        page_revision_count,
        page_seconds_since_previous_revision,

        user_id,
        user_text_historical,
        user_text,
        user_blocks_historical,
        user_blocks,
        user_groups_historical,
        user_groups,
        user_is_bot_by_historical,
        user_is_bot_by,
        user_is_created_by_self,
        user_is_created_by_system,
        user_is_created_by_peer,
        user_is_anonymous,
        user_registration_timestamp,
        user_creation_timestamp,
        user_first_edit_timestamp,

        revision_id,
        revision_parent_id,
        revision_minor_edit,
        revision_deleted_parts,
        revision_deleted_parts_are_suppressed,
        revision_text_bytes,
        revision_text_bytes_diff,
        revision_text_sha1,
        revision_content_model,
        revision_content_format,
        revision_is_deleted_by_page_deletion,
        revision_deleted_by_page_deletion_timestamp,
        revision_is_identity_reverted,
        revision_first_identity_reverting_revision_id,
        revision_seconds_to_identity_revert,
        revision_is_identity_revert,
        revision_is_from_before_page_creation,
        revision_tags
    ) = parts

    return {
        "wiki_db": parse_str(wiki_db),
        "event_entity": parse_str(event_entity),
        "event_type": parse_str(event_type),
        "event_timestamp": parse_date(event_timestamp),
        "event_comment": parse_str(event_comment),

        "event_user_id": parse_int(event_user_id),
        "event_user_text_historical": parse_str(event_user_text_historical),
        "event_user_text": parse_str(event_user_text),
        "event_user_blocks_historical": parse_str_array(event_user_blocks_historical),
        "event_user_blocks": parse_str_array(event_user_blocks),
        "event_user_groups_historical": parse_str_array(event_user_groups_historical),
        "event_user_groups": parse_str_array(event_user_groups),
        "event_user_is_bot_by_historical": parse_str_array(event_user_is_bot_by_historical),
        "event_user_is_bot_by": parse_str_array(event_user_is_bot_by),
        "event_user_is_created_by_self": parse_bool(event_user_is_created_by_self),
        "event_user_is_created_by_system": parse_bool(event_user_is_created_by_system),
        "event_user_is_created_by_peer": parse_bool(event_user_is_created_by_peer),
        "event_user_is_anonymous": parse_bool(event_user_is_anonymous),
        "event_user_registration_timestamp": parse_date(event_user_registration_timestamp),
        "event_user_creation_timestamp": parse_date(event_user_creation_timestamp),
        "event_user_first_edit_timestamp": parse_date(event_user_first_edit_timestamp),
        "event_user_revision_count": parse_int(event_user_revision_count),
        "event_user_seconds_since_previous_revision": parse_int(event_user_seconds_since_previous_revision),

        "page_id": parse_int(page_id),
        "page_title_historical": parse_str(page_title_historical),
        "page_title": parse_str(page_title),
        "page_namespace_historical": parse_int(page_namespace_historical),
        "page_namespace_is_content_historical": parse_bool(page_namespace_is_content_historical),
        "page_namespace": parse_int(page_namespace),
        "page_namespace_is_content": parse_bool(page_namespace_is_content),
        "page_is_redirect": parse_bool(page_is_redirect),
        "page_is_deleted": parse_bool(page_is_deleted),
        "page_creation_timestamp": parse_date(page_creation_timestamp),
        "page_first_edit_timestamp": parse_date(page_first_edit_timestamp),
        "page_revision_count": parse_int(page_revision_count),
        "page_seconds_since_previous_revision": parse_int(page_seconds_since_previous_revision),

        "user_id": parse_int(user_id),
        "user_text_historical": parse_str(user_text_historical),
        "user_text": parse_str(user_text),
        "user_blocks_historical": parse_str_array(user_blocks_historical),
        "user_blocks": parse_str_array(user_blocks),
        "user_groups_historical": parse_str_array(user_groups_historical),
        "user_groups": parse_str_array(user_groups),
        "user_is_bot_by_historical": parse_str_array(user_is_bot_by_historical),
        "user_is_bot_by": parse_str_array(user_is_bot_by),
        "user_is_created_by_self": parse_bool(user_is_created_by_self),
        "user_is_created_by_system": parse_bool(user_is_created_by_system),
        "user_is_created_by_peer": parse_bool(user_is_created_by_peer),
        "user_is_anonymous": parse_bool(user_is_anonymous),
        "user_registration_timestamp": parse_date(user_registration_timestamp),
        "user_creation_timestamp": parse_date(user_creation_timestamp),
        "user_first_edit_timestamp": parse_date(user_first_edit_timestamp),

        "revision_id": parse_int(revision_id),
        "revision_parent_id": parse_int(revision_parent_id),
        "revision_minor_edit": parse_bool(revision_minor_edit),
        "revision_deleted_parts": parse_str_array(revision_deleted_parts),
        "revision_deleted_parts_are_suppressed": parse_bool(revision_deleted_parts_are_suppressed),
        "revision_text_bytes": parse_int(revision_text_bytes),
        "revision_text_bytes_diff": parse_int(revision_text_bytes_diff),
        "revision_text_sha1": parse_str(revision_text_sha1),
        "revision_content_model": parse_str(revision_content_model),
        "revision_content_format": parse_str(revision_content_format),
        "revision_is_deleted_by_page_deletion": parse_bool(revision_is_deleted_by_page_deletion),
        "revision_deleted_by_page_deletion_timestamp": parse_str(revision_deleted_by_page_deletion_timestamp),
        "revision_is_identity_reverted": parse_bool(revision_is_identity_reverted),
        "revision_first_identity_reverting_revision_id": parse_int(revision_first_identity_reverting_revision_id),
        "revision_seconds_to_identity_revert": parse_int(revision_seconds_to_identity_revert),
        "revision_is_identity_revert": parse_bool(revision_is_identity_revert),
        "revision_is_from_before_page_creation": parse_bool(revision_is_from_before_page_creation),
        "revision_tags": parse_str_array(revision_tags)
    }